# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
symbol = "â¯ "
use_symbol_for_status = true

[cmd_duration]
show_milliseconds = true

[directory]
fish_style_pwd_dir_length = 2
truncate_ro_repo = false
